# Generated by Django 4.2.29 on 2026-04-12 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=0)),
                ('release', models.DateField(default=datetime.datetime(2026, 4, 12, 12, 6, 5, 721524, tzinfo=datetime.timezone.utc))),
                ('description', models.TextField()),
                ('steam_url', models.URLField()),
                ('image_url', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
