# Generated by Django 4.2.29 on 2026-05-03 08:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='release',
            field=models.DateField(default=datetime.datetime(2026, 5, 3, 8, 28, 43, 164721, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='GameImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameinfo')),
            ],
        ),
    ]
