# Generated by Django 4.2.29 on 2026-05-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IgromaniaArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igromania_id', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='ID на Игромании')),
                ('slug', models.SlugField(blank=True, max_length=320)),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Текст')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
                ('source_url', models.URLField(max_length=600, verbose_name='Ссылка на материал')),
                ('external_image_url', models.URLField(blank=True, max_length=600, verbose_name='URL обложки (CDN)')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Обложка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Новость Игромании',
                'verbose_name_plural': 'Новости Игромании',
                'ordering': ('-release_date', '-igromania_id'),
            },
        ),
    ]
